Add user email
prjctr-node/user-service pull request #13
Opened 2021-05-03 08:12 UTC by komaryk

2021-05-03 13:08 UTC, welikoiwanenko requested changes
Выглядит круто, надо исправить пару мелочей

2021-05-03 13:08 UTC, welikoiwanenko commented on src/middlewares/router/userRouter.js
> +    await checkExistingUser(email);
Если есть проверка на уникальность почты - надо делать это поле unique в базе

2021-05-03 13:08 UTC, welikoiwanenko commented on src/middlewares/router/userRouter.js
> +    user.email = email;
Можно отрефакторить этот кусок с помощью деструктивного присваивания

2021-05-03 17:55 UTC, lukovskij commented
Обновии ченджі

2021-05-04 10:05 UTC, welikoiwanenko approved these changes
👌🏻

2021-05-04 10:05 UTC, merged